[package]
name = "proj_01_todo_cli"
version = "0.1.0"
edition = "2024"
publish = ["artifactory-remote"]

[[bin]]
name = "proj_01_todo_cli"
path = "src/main.rs"



[dependencies]
clap = { workspace = true }        # CLI arg parsing (like commander/yargs)
serde = { workspace = true }       # (de)serialization framework
serde_json = { workspace = true }  # JSON format for serde
anyhow = { workspace = true }      # ergonomic error handling for the app
